apiVersion: v1
kind: Service
metadata:
  name: capstone-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: capstone
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
